spring:
  application:
    name: clothing_store

  logging:
    level:
      org.springframework: DEBUG
      com.java6.asm.clothing_store: DEBUG

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE}
          max-idle: ${REDIS_POOL_MAX_IDLE}
          min-idle: ${REDIS_POOL_MIN_IDLE}
          max-wait: ${REDIS_POOL_MAX_WAIT}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/auth/google/success}

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

# Cấu hình CORS
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN_1}

# Cấu hình bổ sung để tăng bảo mật
server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:false}
        http-only: true
  port: ${SERVER_PORT:8080}